services:
  admission-db:
    container_name: admission_db
    image: postgres
    ports:
      - '5433:5432'
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nginx_network
  metsenat:
    image: registry.github.com/usmonjonqahhorov/turin_admission/develop:web
    container_name: admission_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - admission-db
    networks:
      - nginx_network

  admission-worker:
    image: registry.ghcr.io/usmonjonqahhorov/turin_admission/develop:web
    container_name: admission_worker
    command: celery --app=config worker -l INFO
    volumes:
      - ./:/usr/src/app/"
    user: root
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - admission-db
    networks:
      - nginx_network
volumes:
  postgres_data:

networks:
  nginx_network:
    external: true