# Generated by Django 4.2.5 on 2025-03-10 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=10, max_digits=100)),
                ('payment_type', models.CharField(choices=[('first', 'Первичная регистрация'), ('second', 'Вторая попытка'), ('third_plus', 'Третья и более')], max_length=50)),
                ('status', models.CharField(choices=[('pending_payment', 'Ожидание платежа'), ('confirmed', 'Оплачено'), ('failed', 'Провален'), ('passed', 'Сдан')], max_length=60)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('click_trans_id', models.IntegerField(null=True)),
                ('service_id', models.IntegerField(null=True)),
                ('click_paydoc_id', models.IntegerField(null=True)),
                ('merchant_trans_id', models.IntegerField(null=True)),
                ('confirmed_at', models.DateField()),
                ('provider', models.CharField(max_length=155)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.clickorder')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.examregistration')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
