# Generated by Django 4.2.5 on 2025-03-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receiver_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
