# Generated by Django 4.2.5 on 2025-03-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_receiver_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='confirmed_at',
            field=models.DateField(null=True),
        ),
    ]
