# Generated by Django 4.2.5 on 2025-03-10 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_remove_payment_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='receiver_id',
            new_name='receipt_id',
        ),
    ]
