# Generated by Django 4.2.5 on 2025-03-13 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_rename_receiver_id_payment_receipt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Ожидание платежа'), ('confirmed', 'Оплачено'), ('failed', 'Провален'), ('canceled', 'Отменено')], max_length=60),
        ),
    ]
