# Generated by Django 4.2.5 on 2025-03-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание платежа'), ('confirmed', 'Оплачено'), ('failed', 'Провален'), ('canceled', 'Отменено')], max_length=60),
        ),
    ]
