# Generated by Django 4.2.5 on 2025-03-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_applicant_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
