# Generated by Django 4.2.5 on 2025-03-10 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_payment_payment_order'),
        ('users', '0004_applicant_deleted_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClickOrder',
        ),
    ]
