# Generated by Django 4.2.5 on 2025-03-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_applicant_certificates_applicant_exam_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='language_certificates',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
