# Generated by Django 4.2.5 on 2025-03-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_applicant_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examregistration',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
