# Generated by Django 4.2.5 on 2025-03-17 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_examregistration_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examregistration',
            name='score',
        ),
    ]
