# Generated by Django 4.2.5 on 2025-03-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_examregistration_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='examregistration',
            name='attempt_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='examregistration',
            name='ball',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='examregistration',
            name='result',
            field=models.BooleanField(null=True),
        ),
        migrations.DeleteModel(
            name='ExamAttempt',
        ),
    ]
