# Generated by Django 4.2.5 on 2025-03-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_examregistration_attempt_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examregistration',
            name='attempt_number',
        ),
        migrations.AlterField(
            model_name='examregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание платежа'), ('confirmed', 'Оплачено'), ('failed', 'Провален'), ('canceled', 'Отменено')], default='pending', max_length=20),
        ),
    ]
