# Generated by Django 4.2.5 on 2025-03-18 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_examregistration_attempt_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='exam_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.examdate'),
        ),
        migrations.RemoveField(
            model_name='program',
            name='exam_date',
        ),
        migrations.AddField(
            model_name='program',
            name='exam_date',
            field=models.ManyToManyField(related_name='programs', to='users.examdate'),
        ),
    ]
