# Generated by Django 4.2.5 on 2025-03-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_applicant_exam_date_remove_program_exam_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='exam_date',
            field=models.ManyToManyField(related_name='program_exam_date', to='users.examdate'),
        ),
    ]
