# Generated by Django 4.2.5 on 2025-03-18 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_program_exam_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='exam_date',
        ),
        migrations.CreateModel(
            name='ProgramExamdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_dates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_date_program', to='users.examdate')),
                ('programs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_exam', to='users.program')),
            ],
        ),
    ]
